# Dockerfile.dev

FROM node:18

WORKDIR /usr/src/app

# Install all dependencies including dev dependencies
COPY package*.json ./
RUN npm ci

# Copy all source code (with volume override in development, this step might be skipped)
COPY . .

#allow for listening on docker network, but don't expose to main server
EXPOSE 3000

# Use the Next.js development command
CMD ["npm", "run", "dev:frontend"]
