# Dockerfile.dev

FROM node:18

WORKDIR /usr/src/app

# Install all dependencies including dev dependencies
COPY package*.json ./
RUN npm install

# Copy all source code (with volume override in development, this step might be skipped)
COPY . .

ENV HOST=0.0.0.0
EXPOSE 3000

# Use the Next.js development command
CMD ["npm", "run", "dev:frontend"]
